archive:
	cd .. && mv webapp word-intrusion-study && tar hczf word-intrusion-study/word-intrusion-study.tgz word-intrusion-study/requirements.txt word-intrusion-study/web.py word-intrusion-study/templates word-intrusion-study/static word-intrusion-study/out/word-intrusion word-intrusion-study/glossary && mv word-intrusion-study webapp && cd webapp
